title: "Tech-Wyatt"
author: "Wyatt Anderson"
description: "Tech enthusiast writing about what I find interesting in the world."
url: "https://wyattx05.github.io"
baseurl: "/Tech-Wyatt"

email: "whanderson024@gmail.com"
portfolio_url: "https://wyattx05.github.io/Portfolio/"

#########################################################################################
######### Nothing below needs to be changed (unless you know what you're doing) #########
#########################################################################################
theme: "minima"

header_pages:
  - archive.md

minima:
  social_links:
    - { title: "GitHub", icon: "github", url: "https://github.com/wyattx05" }
    - { title: "LinkedIn", icon: "linkedin", url: "https://www.linkedin.com/in/wyatt-anderson609/" }
    - { title: "YouTube", icon: "youtube", url: "https://www.youtube.com/@techwyatt" }

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap

defaults:
  - scope:
      path: ""
      type: post
    values:
      tags: Other
